[package]
name = "polaris"
version = "2.0.0"
edition = "2024"

[profile.dev]
panic = "abort"
lto = false

[profile.dev.package."*"]
opt-level = 2

[profile.release]
panic = "abort"
opt-level = 2

[dependencies]
limine = { path = "limine-rs" }
flanterm = { path = "flanterm-rs", default-features = false }
bitflags = "2.13.1"
intrusive-collections = { version = "0.10.3", default-features = false, features = ["alloc"] }
seq-macro = "0.3.6"
enum_dispatch = "0.3.13"

[workspace]
members = ["limine-rs", "flanterm-rs"]
