timeout: 2

/Polaris
//Polaris
protocol: limine
kaslr: no
path: boot():/polaris.elf
cmdline: kprintf
module_path: boot():/ramdisk.tar

//Polaris (Panic on deadlock)
protocol: limine
kaslr: no
path: boot():/polaris.elf
cmdline: kprintf panic-on-deadlock
module_path: boot():/ramdisk.tar

//Polaris (Silence user debug messages)
protocol: limine
kaslr: no
path: boot():/polaris.elf
cmdline: kprintf suppress-user-debug-messages
module_path: boot():/ramdisk.tar
