timeout: 2

/Polaris
//Polaris
protocol: limine
kaslr: no
path: boot():/polaris.elf
cmdline: kprintf allow-writes-to-disks
module_path: boot():/ramdisk.tar

//Polaris (Panic on deadlock)
protocol: limine
kaslr: no
path: boot():/polaris.elf
cmdline: kprintf allow-writes-to-disks panic-on-deadlock
module_path: boot():/ramdisk.tar

//Polaris (Silence user debug messages)
protocol: limine
kaslr: no
path: boot():/polaris.elf
cmdline: kprintf allow-writes-to-disks panic-on-deadlock suppress-user-debug-messages
module_path: boot():/ramdisk.tar