#ifndef PRINTF_CONFIG_H_
#define PRINTF_CONFIG_H_

#define PRINTF_SUPPORT_DECIMAL_SPECIFIERS 0
#define PRINTF_SUPPORT_EXPONENTIAL_SPECIFIERS 0
#define PRINTF_SUPPORT_MSVC_STYLE_INTEGER_SPECIFIERS 0

#endif // PRINTF_CONFIG_H_
